swagger: "2.0"
info:
  title: 物供系统接口文档
  description: 物供系统所有的接口都会在该文档中进行说明
basePath: /1
paths:
  /ceshis/wenjianliu:
    post:
      tags:
      - ceshis
      description: wenjianliu 做的时候记得把登录注释了*******************************
      parameters:
      - in: body
        name: body
        description: 请求参数说明
        required: true
        schema:
          $ref: '#/definitions/controllers.Zhi'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.Zhi'
        "201":
          description: '{"err_code":"错误编码值","err_msg":"错误描述值"}'
  /golang_mysql_lock/lock_optimi:
    post:
      tags:
      - golang_mysql_lock
      description: 乐观锁*******************************
      parameters:
      - in: body
        name: body
        description: 请求参数说明
        required: true
        schema:
          $ref: '#/definitions/controllers.Zhi'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.Zhi'
        "201":
          description: '{"err_code":"错误编码值","err_msg":"错误描述值"}'
  /golang_mysql_lock/lock_pessimi:
    post:
      tags:
      - golang_mysql_lock
      description: 悲观锁 的 共享*******************************
      parameters:
      - in: body
        name: body
        description: 请求参数说明
        required: true
        schema:
          $ref: '#/definitions/controllers.Zhi'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.Zhi'
        "201":
          description: '{"err_code":"错误编码值","err_msg":"错误描述值"}'
  /golang_mysql_lock/lock_pessimi_for:
    post:
      tags:
      - golang_mysql_lock
      description: 悲观锁 的 排他*******************************
      parameters:
      - in: body
        name: body
        description: 请求参数说明
        required: true
        schema:
          $ref: '#/definitions/controllers.Zhi'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.Zhi'
        "201":
          description: '{"err_code":"错误编码值","err_msg":"错误描述值"}'
definitions:
  controllers.Zhi:
    title: Zhi
    type: object
    properties:
      board_id:
        description: 角色ID
        type: string
      id:
        description: 角色ID
        type: integer
        format: int64
